SpecificUrlNavigation/urls.py
from django.contrib import admin
from django.urls import path,include
import csk , rcb
urlpatterns = [
    path('admin/', admin.site.urls),
    path('csk/',include('csk.urls')),
    path('rcb/',include('rcb.urls')),
]

csk/urls.py
from django.urls import path
from csk.views import *
app_name = 'cskteam'
urlpatterns  = [
    path('doni/',doni,name='doni'),
]

rcb/urls.py
from django.urls import path
from rcb.views import *
app_name = 'rcbteam'
urlpatterns = [
    path('virat/',virat,name='virat'),
]

csk/models.py
from django.db import models

# Create your models here.

rcb/models.py
from django.db import models

# Create your models here.

csk/views.py
from django.shortcuts import render

# Create your views here.
def doni(request):
    return render(request,'doni.html')

rcb/views.py
from django.shortcuts import render

# Create your views here.
def virat(request):
    return render(request,'virat.html')

templates/doni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Doni:- The Passion which u r putting towards game is incredible and unmatchable..</h1>
        <h1>So , How manage your diet to this type of energy and consistency</h1>
       <h1> <a href="{% url 'rcbteam:virat' %}">virat resopse</a></h1>
    </center>
</body>
</html>

templates/virat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Thank U Msd for valuable comments ..and there no perticular diet for my game 
        iam always wanted score runs for my nation
    </h1>
    <h1><a href="{% url 'cskteam:doni' %}">doni response</a></h1>
    </center>
</body>
</html>